{include file="common/header"}
<div class="content-wrapper">
    {include file="channel/nav"/}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    {include file="channel/tabs"/}
                    <div class="tab-content">
                        <form method="post" class="form-horizontal form" id="post_form">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                 添加通道
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">通道名称</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="name" value="{$item['name']?$item['name']:''}" placeholder="请输入渠道名称">
                                        </div>
                                    </div>
									<div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">标识</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="Identification" value="{$item['Identification']?$item['Identification']:''}" placeholder="请输入渠道名称">
                                        </div>
                                    </div>
									
                                            <div class="form-group">
												<label class="col-xs-12 col-sm-3 col-md-2 control-label">app_id</label>
												<div class="col-sm-6 col-xs-12">
													<input type="text" class="form-control" name="app_id" value="{$item['app_id']?$item['app_id']:''}" placeholder="请输入渠道名称">
												</div>
											</div>
											 <div class="form-group">
												<label class="col-xs-12 col-sm-3 col-md-2 control-label">支付宝公钥</label>
												<div class="col-sm-6 col-xs-12">
												<textarea  name="alipay_public_key" placeholder="请输入支付宝公钥" rows="8" cols="50">{$item['alipay_public_key']?$item['alipay_public_key']:''}</textarea>
													
												</div>
											</div>
											 <div class="form-group">
												<label class="col-xs-12 col-sm-3 col-md-2 control-label">商户私钥</label>
												<div class="col-sm-6 col-xs-12">
													<textarea name="merchant_private_key" placeholder="请输入支付宝商户私钥" rows="8" cols="50">{$item['merchant_private_key']?$item['merchant_private_key']:''}</textarea>
												</div>
											</div>
                                    
									<div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">查看地址</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="url" value="{$item['url']?$item['url']:''}" placeholder="请输入渠道名称">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">排序</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="number" class="form-control" name="order_by" placeholder="请输入数字，越大排序越靠前" value="{$item['order_by']?$item['order_by']:0}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">状态</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <label class="radio-inline">
                                                <input type="radio" name="is_display" value="1" {$item['is_display']?'checked':''}>
                                                显示
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="is_display" value="0" {$item['is_display']?'':'checked'}>
                                                隐藏
                                            </label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-xs-12 col-sm-offset-2">
                                            <input type="hidden" name="id" value="{$item['id']?$item['id']:0}">
                                            <button type="button" name="submit" class="btn btn-primary">提交</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <script type="text/javascript">
                            $(function () {
                                //提交分类信息
                                $("button[name='submit']").click(function () {
                                    $.post(
                                        window.location.href,
                                        $('#post_form').serialize(),
                                        function (res) {
                                            message(res.message,res.redirect,res.type)
                                        },'json'
                                    );
                                });
                            });
                        </script>
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</div>
{include file="common/footer"}
